pipeline {
    agent any

    stages {
        agent {
            docker {
                image 'node:18-alpine'
                reuseNode true
            }
        }
        stage('Hello') {
            steps {
                sh '''
                npm ci
                npm run build
                '''
            }
        }
    }
}
